//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BooksLibraryDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BooksTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BooksTable()
        {
            this.LendsTable = new HashSet<LendsTable>();
            this.MyBasketOfBooks = new HashSet<MyBasketOfBooks>();
            this.waitingForAbookTable = new HashSet<waitingForAbookTable>();
            this.RatingTable = new HashSet<RatingTable>();
        }
    
        public int nameId { get; set; }
        public int id { get; set; }
        public int categoryId { get; set; }
        public int publishingId { get; set; }
        public string description { get; set; }
        public bool isBorrowed { get; set; }
        public int lenderId { get; set; }
        public int autherId { get; set; }
        public int numOfPages { get; set; }
        public string picNAme { get; set; }
        public int numberOfViewers { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    
        public virtual AutherTable AutherTable { get; set; }
        public virtual BooksCategriesTable BooksCategriesTable { get; set; }
        public virtual BooksNameTable BooksNameTable { get; set; }
        public virtual PublishingTable PublishingTable { get; set; }
        public virtual UsersTable UsersTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LendsTable> LendsTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MyBasketOfBooks> MyBasketOfBooks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<waitingForAbookTable> waitingForAbookTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RatingTable> RatingTable { get; set; }
    }
}
