//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BooksLibraryDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BooksLibraryProjectEntities : DbContext
    {
        public BooksLibraryProjectEntities()
            : base("name=BooksLibraryProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AutherTable> AutherTable { get; set; }
        public virtual DbSet<BooksCategriesTable> BooksCategriesTable { get; set; }
        public virtual DbSet<BooksNameTable> BooksNameTable { get; set; }
        public virtual DbSet<CityTable> CityTable { get; set; }
        public virtual DbSet<GenderTable> GenderTable { get; set; }
        public virtual DbSet<KealYhadTable> KealYhadTable { get; set; }
        public virtual DbSet<LendsTable> LendsTable { get; set; }
        public virtual DbSet<PublishingTable> PublishingTable { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<UsersTable> UsersTable { get; set; }
        public virtual DbSet<MyBasketOfBooks> MyBasketOfBooks { get; set; }
        public virtual DbSet<lendsStatusTable> lendsStatusTable { get; set; }
        public virtual DbSet<waitingForAbookTable> waitingForAbookTable { get; set; }
        public virtual DbSet<BookPicsTable> BookPicsTable { get; set; }
        public virtual DbSet<BooksTable> BooksTable { get; set; }
        public virtual DbSet<RatingTable> RatingTable { get; set; }
    }
}
