//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BooksLibraryDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LendsTable
    {
        public int id { get; set; }
        public int borrowerId { get; set; }
        public int bookId { get; set; }
        public System.DateTime date { get; set; }
        public bool bookIsActive { get; set; }
        public int statusCode { get; set; }
    
        public virtual UsersTable UsersTable { get; set; }
        public virtual lendsStatusTable lendsStatusTable { get; set; }
        public virtual BooksTable BooksTable { get; set; }
    }
}
