//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BooksLibraryDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RatingTable
    {
        public int id { get; set; }
        public Nullable<int> borrowerId { get; set; }
        public Nullable<int> rating { get; set; }
        public string desk { get; set; }
        public Nullable<int> kealYhad { get; set; }
        public int bookId { get; set; }
        public Nullable<System.DateTime> dateInsert { get; set; }
    
        public virtual BooksTable BooksTable { get; set; }
        public virtual KealYhadTable KealYhadTable { get; set; }
        public virtual UsersTable UsersTable { get; set; }
    }
}
