//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BooksLibraryDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class waitingForAbookTable
    {
        public int id { get; set; }
        public int userCode { get; set; }
        public int bookCode { get; set; }
        public Nullable<int> bookOwnerID { get; set; }
    
        public virtual UsersTable UsersTable { get; set; }
        public virtual UsersTable UsersTable1 { get; set; }
        public virtual BooksTable BooksTable { get; set; }
    }
}
